name: Release Charts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - "./**"
    - ".github/workflows/helm-release.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602058369
    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0-rc.2
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"
      with: 
        charts_repo_url: https://ninjaneers-team.github.io/activemq-artemis-helm
        charts_dir: ./
